# Generated by Django 2.2.9 on 2020-06-14 08:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type_qs', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('ques', models.CharField(max_length=255)),
                ('corr_ans', models.CharField(max_length=100)),
                ('ans', django_mysql.models.ListTextField(models.CharField(max_length=100), max_length=404, size=4)),
            ],
        ),
    ]
