# Generated by Django 2.2.9 on 2020-06-15 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type_qs', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('ques', models.CharField(max_length=255)),
                ('corr_ans', models.CharField(max_length=100)),
                ('ans', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=4)),
            ],
        ),
    ]
